/**
 * Formats markdown text for WhatsApp sharing
 * Converts markdown formatting to WhatsApp-compatible text
 */
export function formatForWhatsApp(markdown: string, tripName: string): string {
  // Convert markdown to WhatsApp-friendly format
  let formatted = markdown
    // Remove markdown headers and replace with emojis
    .replace(/^### (.*$)/gm, "📊 *$1*")
    .replace(/^## (.*$)/gm, "📈 *$1*")
    .replace(/^# (.*$)/gm, "🧾 *$1*")

    // Convert bold markdown to WhatsApp bold
    .replace(/\*\*(.*?)\*\*/g, "*$1*")

    // Convert italic markdown to WhatsApp italic
    .replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, "_$1_")

    // Convert tables to readable format
    .replace(/\|/g, " │ ")
    .replace(/^-+\s*\|\s*-+.*$/gm, "├─────────────────────┤")

    // Clean up extra whitespace and line breaks
    .replace(/\n{3,}/g, "\n\n")
    .replace(/^\s+|\s+$/gm, "")
    .trim();

  // Add header and footer
  const header = `🧾 *${tripName} - Expense Summary*\n${"═".repeat(30)}\n\n`;
  const footer = `\n${"═".repeat(
    30
  )}\n📱 _Generated by Trip Expense Manager_\n🔗 https://trip.debmalya.in`;

  return header + formatted + footer;
}

/**
 * Creates a WhatsApp share URL with the formatted message
 */
export function createWhatsAppShareUrl(
  message: string,
  phoneNumber?: string
): string {
  const encodedMessage = encodeURIComponent(message);

  if (phoneNumber) {
    // Share to specific contact
    return `https://wa.me/${phoneNumber}?text=${encodedMessage}`;
  } else {
    // Open WhatsApp with message ready to share
    return `https://wa.me/?text=${encodedMessage}`;
  }
}

/**
 * Truncates message if it's too long for WhatsApp (max ~4096 characters)
 */
export function truncateForWhatsApp(
  message: string,
  maxLength: number = 4000
): string {
  if (message.length <= maxLength) {
    return message;
  }

  const truncated = message.substring(0, maxLength - 100);
  const lastNewline = truncated.lastIndexOf("\n");

  return (
    truncated.substring(0, lastNewline) +
    "\n\n... (Summary truncated for WhatsApp)\n\n📱 _View full summary in the app_"
  );
}
